default_stages: [commit, push]
fail_fast: false
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
      - id: poetry-export  # Dev dependencies
        args: ["-f", "requirements.txt", "-o", "requirements_dev.txt", "--with", "dev", "--without-hashes"]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: docs/conf.py
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: .bumpversion.cfg
      - id: mixed-line-ending
        args: ['--fix=no']
      - id: trailing-whitespace
  - repo: https://github.com/szebenyib/pre-commit-pytest
    rev: 051fea31dbabf063ab38428c34a92c76d1abd5dc
    hooks:
    - id: pytest
      args: ['--cov-config=.coveragerc', '--cov-branch', '--cov=pyetrade', '--cov-fail-under', '90',
             '--cov-report', 'term-missing', '--cov-report', 'xml', 'tests/']
