version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "latest"
python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_dev.txt
sphinx:
  builder: html
  configuration: docs/conf.py
formats:
  - epub
  - pdf
